### PR TITLE
Parse encryption_info and encryption_info_64

### PR DESCRIPTION
**Pull request by trufae**

### CODE REVIEW

**Comment by indutny** [comment]
Wow, thank you so much for this! Do you think we could have a test case for this feature?

**Comment by trufae** [comment]
Encrypted apps are only available in the AppStore and cannot be
distributed. We can tweak an already existing mach0 binary if you want a
testsuite.

**Comment by indutny** [comment]
Oh... I see. May I at least get your word on it? ;)

**Comment by trufae** [comment]
Yeah, you have my word on it :) but all those structures are documented in the include files of mach0 and can be verified with tools like `otool` or `radare2`

**Comment by indutny** [comment]
LGTM. I have actually checked it before asking for your word :wink:

**Comment by indutny** [comment]
Landed and released, thank you!

**Comment by trufae** [comment]
👍

**Pull request closed without merging**
