### PR TITLE
Expose physical address of each mach0 load command

### PR DESCRIPTION
**Pull request by trufae**

### CODE REVIEW

**Comment by radare** [comment]
Should it be named `fileoff` instead? or maybe `_fileOffset` to denote that this field is not coming from the header itself, but from the parsing. Also, that 32 is a hardcoded `fileheader.length`

**Comment by trufae** [comment]
Should it be named `fileoff` instead? or maybe `_fileOffset` to denote that this field is not coming from the header itself, but from the parsing. Also, that 32 is a hardcoded `fileheader.length`

**Comment by trufae** [comment]
ping

**Comment by indutny** [comment]
Heya!

Thanks for opening this. I'd call it `fileoff`.

**Comment by trufae** [comment]
for consistency I would go for fileOffset, camelcasing instead of shortening and merging words

**Comment by trufae** [comment]
Yeah, `fileoff` makes sense. i have updated the PR

**Comment by radare** [comment]
ping

**Comment by indutny** [comment]
Pong, landing. Sorry!

**Comment by indutny** [comment]
Landed and released in 1.1.0, thank you!

**Comment by radare** [comment]
👍

**Pull request closed without merging**
